# https://docs.github.com/en/discussions/managing-discussions-for-your-community/syntax-for-discussion-category-forms

title: "[Suggestion] "
labels: ["suggestion"]
body:
  - type: input
    id: suggestion
    attributes:
      label: Suggestion
      description: "How might we make this project better?"
      placeholder: "Adding a CODE_OF_CONDUCT.md file would be a great idea."
    validations:
      required: true
