name: Release
description: Tags Docker image and creates a GitHub release

inputs:
  sha:
    description: The commit SHA to tag
    required: true
  version:
    description: The version to release
    required: true
  image:
    description: The image name without tag (e.g. ghcr.io/org/repo)
    required: false

runs:
  using: composite
  steps:
    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
        SHA: ${{ inputs.sha }}
        VERSION: ${{ inputs.version }}
      shell: bash
      run: |
        echo "Creating release v${VERSION}..."
        if gh release view "v${VERSION}" > /dev/null 2>&1; then
          echo "Release v${VERSION} already exists. Skipping creation."
        else
          gh release create "v${VERSION}" \
            --title "Version ${VERSION}" \
            --notes "Released via GitHub Actions" \
            --target "$SHA"
        fi

    - name: Docker login (if image provided)
      if: ${{ inputs.image != '' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Tag & Push Docker Image
      if: ${{ inputs.image != '' }}
      shell: bash
      run: |
        echo "Tagging and pushing Docker image ${{ inputs.image }}:${{ inputs.version }}"
        docker pull "${{ inputs.image }}:latest"
        docker tag "${{ inputs.image }}:latest" "${{ inputs.image }}:${{ inputs.version }}"
        docker push "${{ inputs.image }}:${{ inputs.version }}"
