name: Release
description: Tags and releases a GitHub repository

inputs:
  sha:
    description: The commit SHA to tag
    required: true
  version:
    description: The version to release
    required: true

runs:
  using: composite
  steps:
    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
        SHA: ${{ inputs.sha }}
        VERSION: ${{ inputs.version }}
      shell: bash
      run: |
        echo "Creating release v${VERSION}..."
        gh release create "v${VERSION}" \
          --title "Version ${VERSION}" \
          --notes "Released via GitHub Actions" \
          --target $SHA
