name: Release
description: Tags Docker image and creates a GitHub release

inputs:
  sha:
    description: The commit SHA to tag
    required: true
  version:
    description: The version to release
    required: true
  image:
    description: The image name without tag (e.g. ghcr.io/org/repo)
    required: false

runs:
  using: "composite"
  steps:
    - name: Create GitHub Release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        SHA: ${{ inputs.sha }}
        VERSION: ${{ inputs.version }}
      run: |
        echo "🔖 Creating GitHub release for v${VERSION}..."
        if gh release view "v${VERSION}" > /dev/null 2>&1; then
          echo "✅ Release v${VERSION} already exists. Skipping release step."
        else
          gh release create "v${VERSION}" \
            --title "Version ${VERSION}" \
            --notes "Released via GitHub Actions" \
            --target "$SHA"
        fi

    - name: Login to GHCR
      if: ${{ inputs.image != '' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Tag and Push Docker Image
      if: ${{ inputs.image != '' }}
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        VERSION: ${{ inputs.version }}
      run: |
        echo "🐳 Tagging Docker image $IMAGE:$VERSION"

        docker pull "$IMAGE:latest" || {
          echo "❌ Failed to pull latest image. Aborting tag step.";
          exit 1;
        }

        docker tag "$IMAGE:latest" "$IMAGE:$VERSION"
        docker push "$IMAGE:$VERSION"
