name: Detect Version
description: Detects the version within the source code per the language detected

inputs:
  regex:
    description: The regex to use to match the version
    required: false
    default: '[0-9]*\.[0-9]*\.[0-9]*'

outputs:
  current:
    description: The current version of the project
    value: ${{ steps.current.outputs.version }}

runs:
  using: composite
  steps:
    - name: Check for JavaScript
      if: hashFiles('package.json') != ''
      shell: bash
      run: |
        echo "JavaScript detected."
        detected_version=$(grep -oP '"version": "\K'${{ inputs.regex }} package.json)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for .NET
      if: hashFiles('*.csproj') != ''
      shell: bash
      run: |
        echo ".NET detected."
        for file in *.csproj; do
          [ -e "$file" ] || continue
          detected_version=$(grep -oP '<Version>\K'${{ inputs.regex }} "$file")
          echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV
        done

    - name: Check for .NET
      if: hashFiles('Directory.Build.props') != ''
      shell: bash
      run: |
        echo ".NET detected."
        detected_version=$(grep -oP '<Version>\K'${{ inputs.regex }} Directory.Build.props)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Python
      if: hashFiles('setup.py') != ''
      shell: bash
      run: |
        echo "Python detected."
        detected_version=$(grep -oP "version='\K${{ inputs.regex }}" setup.py)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Python
      if: hashFiles('pyproject.toml') != ''
      shell: bash
      run: |
        echo "Python detected."
        detected_version=$(grep -oP 'version = "\K'${{ inputs.regex }} pyproject.toml)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Java
      if: hashFiles('build.gradle') != ''
      shell: bash
      run: |
        echo "Java detected."
        detected_version=$(grep -oP 'version = "\K'${{ inputs.regex }} build.gradle)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Check for Kotlin
      if: hashFiles('build.gradle.kts') != ''
      shell: bash
      run: |
        echo "Kotlin detected."
        detected_version=$(grep -oP 'version = "\K'${{ inputs.regex }} build.gradle.kts)
        echo "DETECTED_VERSION=$detected_version" >> $GITHUB_ENV

    - name: Output Detected Version
      id: current
      shell: bash
      run: |
        if [ -n "$DETECTED_VERSION" ]; then
          echo "Detected Version: $DETECTED_VERSION"
          echo "version=$DETECTED_VERSION" >> $GITHUB_OUTPUT
        else
          echo "No version detected!"
        fi
