name: Deploy
description: Deploy a GitHub environment

inputs:
  environment:
    description: Environment to deploy to
    default: production

runs:
  using: composite
  steps:
    - uses: actions/github-script@v7
      env:
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
      with:
        github-token: ${{ github.token }}
        script: |
          const env = core.getInput('environment');
          console.log(`Deploying to ${env}...`);
          const response = await github.rest.repos.createDeployment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.payload?.pull_request?.head?.ref || 'main',
            required_contexts: [],
            environment: env,
            transient_environment: env === 'preview',
            description: `Deploying to ${env}...`
          });
          console.log(`  Deployment created with ID: ${response.data.id}`);
