on:
  pull_request:
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
      - synchronize
    branches:
      - $default-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  packages: write
  attestations: write
  id-token: write
  deployments: write

name: Integration

jobs:
  lint:
    if: ${{ !contains(fromJSON('["labeled", "unlabeled"]'), github.event.action) }}
    name: Integrate
    uses: gitops-ziichat/.github/.github/workflows/lint.yaml@main

  test:
    if: ${{ !contains(fromJSON('["labeled", "unlabeled"]'), github.event.action) }}
    name: Integrate
    uses: gitops-ziichat/.github/.github/workflows/test.yaml@main

  bump:
    name: Integrate
    uses: gitops-ziichat/.github/.github/workflows/bump.yaml@main

  auto-merge:
    name: Check auto-merge
    uses: gitops-ziichat/.github/.github/workflows/auto_merge.yaml@main

  deploy:
    if: github.event.action == 'labeled' && github.event.label.name == 'preview' || github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'preview')
    name: Deploy
    uses: gitops-ziichat/.github/.github/workflows/deploy.yaml@main
    with:
      environment: preview

  build:
    needs: deploy
    name: Build
    uses: gitops-ziichat/.github/.github/workflows/build.yaml@main
