# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        default: production

permissions:
  deployments: write

name: Deploy

jobs:
  deploy:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Github Deployment
        uses: gitops-ziichat/.github/actions/deploy@main
        with:
          environment: ${{ inputs.environment }}
