# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions

on:
  workflow_call:

permissions:
  contents: read

name: Lint

jobs:
  lint:
    if: ${{ !contains(fromJSON('["labeled", "unlabeled"]'), github.event.action) }}
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Cache
        uses: docker/build-push-action@v6
        with:
          context: .
          target: builder
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Lint
        run: docker compose run --rm lint
