name: Notify Dispatcher

on:
  workflow_call:
    secrets:
      discord_webhook:
        required: true

jobs:
  dispatch:
    name: Collect Failure Info and Notify
    runs-on: ubuntu-latest
    steps:
      - name: Parse Failed Jobs
        id: parse
        run: |
          echo "❌ Collecting failed jobs..."
          echo '${{ inputs.failed_jobs_json }}' > needs.json

          echo "FAILED_JOBS<<EOF" >> $GITHUB_ENV
          cat needs.json | jq -r 'to_entries[] | select(.value.result != "success") | "- \(.key) ❌ (\(.value.result))"' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Discord Notification
        uses: gitops-ziichat/.github/actions/notify-discord@main
        with:
          discord_webhook: ${{ secrets.discord_webhook }}
          deployment_status: "${{ steps.failed.outputs.FAILED_JOBS }}"
          tests_passed: "❌"

      - name: Auto-Close PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close "${{ github.event.pull_request.number }}" \
            -R "$GITHUB_REPOSITORY" \
            --delete-branch \
            --comment "❌ CI failed. PR auto-closed."