name: Notify PR Events to Discord

on:
  workflow_call:
    inputs:
      deployment_status:
        required: false
        type: string
        default: ""
      tests_passed:
        required: false
        type: string
        default: ""
    secrets:
      discord_webhook:
        required: true

jobs:
  notify:
    name: Send Discord Notification
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: gitops-ziichat/.github/actions/notify_discord@main
        with:
          discord_webhook: ${{ secrets.discord_webhook }}
          deployment_status: ${{ inputs.deployment_status }}
          tests_passed: ${{ inputs.tests_passed }}
